// Auht
export const FETCHING_AUTHENTICATION = "FETCHING_AUTHENTICATION";
export const RECEIVE_AUTHENTICATION = "RECEIVE_AUTHENTICATION";
export const CLEAR_AUTHENTICATION = "CLEAR_AUTHENTICATION";
export const REFRESH_ACCESS_TOKEN = "REFRESH_ACCESS_TOKEN";
// Todo Categories Filter
export const REQUEST_FETCH_ALL_CATEGORIES = "REQUEST_FETCH_ALL_CATEGORIES";
export const RECEIVE_FETCH_ALL_CATEGORIES = "RECEIVE_FETCH_ALL_CATEGORIES";
export const ERROR_FETCH_ALL_CATEGORIES = "ERROR_FETCH_ALL_CATEGORIES";
export const ADD_CATEGORY_LOCAL = "ADD_CATEGORY_LOCAL";
export const REMOVE_CATEGORY_LOCAL = "REMOVE_CATEGORY_LOCAL";
export const TOOGLE_SELECT_CATEGORY = "TOOGLE_SELECT_CATEGORY";
export const TOOGLE_SELECT_CATEGORY_ALL = "TOOGLE_SELECT_CATEGORY_ALL";
// Todo Visibility Filter
export const SWITCH_VISIBILITY_FILTER = "SWITCH_VISIBILITY_FILTER";
// Task
export const REQUEST_FETCH_TASKS = "REQUEST_FETCH_TASKS";
export const RECEIVE_FETCH_TASKS = "RECEIVE_FETCH_TASKS";
export const ERROR_FETCH_TASKS = "ERROR_FETCH_TASKS";
export const ADD_TASK_LOCAL = "ADD_TASK_LOCAL";
export const REMOVE_TASK_LOCAL = "REMOVE_TASK_LOCAL";
export const UPDATE_TASK_LOCAL = "UPDATE_TASK_LOCAL";
// Message
export const SHOW_MESSAGE_INFO = "SHOW_MESSAGE_INFO";
export const SHOW_MESSAGE_ERROR = "SHOW_MESSAGE_ERROR";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
