// Todo Categories Filter
export const REQUEST_FETCH_ALL_CATEGORIES = 'REQUEST_FETCH_ALL_CATEGORIES';
export const RECEIVE_FETCH_ALL_CATEGORIES = 'RECEIVE_FETCH_ALL_CATEGORIES';
export const ERROR_FETCH_ALL_CATEGORIES = 'ERROR_FETCH_ALL_CATEGORIES';
export const ADD_CATEGORY_LOCAL = 'ADD_CATEGORY_LOCAL';
export const REMOVE_CATEGORY_LOCAL = 'REMOVE_CATEGORY_LOCAL';
export const TOOGLE_SELECT_CATEGORY = 'TOOGLE_SELECT_CATEGORY';
export const TOOGLE_SELECT_CATEGORY_ALL = 'TOOGLE_SELECT_CATEGORY_ALL';
// Todo Visibility Filter
export const SWITCH_VISIBILITY_FILTER = 'SWITCH_VISIBILITY_FILTER';
// Todo Arguments
export const REQUEST_FETCH_ARGUMENTS = 'REQUEST_FETCH_ARGUMENTS';
export const RECEIVE_FETCH_ARGUMENTS = 'RECEIVE_FETCH_ARGUMENTS';
export const ERROR_FETCH_ARGUMENTS = 'ERROR_FETCH_ARGUMENTS';
export const ADD_ARGUMENT_LOCAL = 'ADD_ARGUMENT_LOCAL';
export const REMOVE_ARGUMENT_LOCAL = 'REMOVE_ARGUMENT_LOCAL';
export const UPDATE_ARGUMENT_LOCAL = 'UPDATE_ARGUMENT_LOCAL';
// Message
export const SHOW_MESSAGE_INFO = 'SHOW_MESSAGE_INFO';
export const SHOW_MESSAGE_ERROR = 'SHOW_MESSAGE_ERROR';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
