export const UNAUTHORIZED = 800;
export const EXPIRED_SESSION = 801;

export const AUTH_INVALID_PAYLOAD = 900;
export const AUTH_INVALID_CODE = 901;
export const ERROR_CREATE_USER = 940;
export const ERROR_CREATE_SESSION = 950;
export const AUTH_ERROR_UNKNOWN = 999;

export const ERROR_READ_CATEGORY = 1001;
export const ERROR_INSERT_CATEGORY = 1002;
export const ERROR_DELETE_CATEGORY = 1003;
export const ERROR_READ_TASK = 1004;
export const ERROR_INSERT_TASK = 1005;
export const ERROR_DELETE_TASK = 1006;
export const ERROR_UPDATE_TASK = 1007;

export const INVALID_AUTH_CODE = 1900;
export const INVALID_CATEGORY_PARAMETERS = 2001;
export const INVALID_CATEGORY_ID = 2002;
export const INVALID_TASK_PARAMETERS = 2003;
export const INVALID_TASK_ID = 2004;
