const labels = {
  titleAdd: "What would you like to add?",
  titleAddCategory: "Add new CATEGORY",
  titleAddTask: "Add new Task",
  titleChooseCategory: "Choose a CATEGORY",
  titleTodoWithin: "Todo Within",
  labelForCategory: "for the category:",
  labelDone: "Done!",
  labelCategory: "CATEGORY",
  labelTask: "TASK",
  labelNotSet: "not set",
  labelNoDescription: "No description to show :(",
  labelPartialCompleted: "completed",
  labelPartialToCompleted: "to complete within",
  placeHolderTitle: "Type the title",
  placeHolderDescription: "Type the description",
  placeholderName: "Type the name",
  buttonSchedule: "SCHEDULE",
  buttonAdd: "ADD",
  buttonNext: "NEXT",
  buttonBack: "NEVER MIND, GO BACK",
  msgTitleRequired: "Enter the title",
  msgNameRequired: "Enter the name",
  msgSelectCategory: "Select a category",
  msgSelectDate: "Pick a date and commit. No excuses!",
  stepDescWantToAdd: "What want to add",
  stepDescAddCategory: "Add a category",
  stepDescrSelecCategory: "Select a category",
  stepDescAddTask: "Add task",
  stepDescCompleteDate: "Schedule",
  stepDescDone: "That's it"
};

export default labels;
