const UNAUTHORIZED = 800;
const EXPIRED_SESSION = 801;

const AUTH_INVALID_PAYLOAD = 900;
const AUTH_INVALID_CODE = 901;
const ERROR_CREATE_USER = 940;
const ERROR_CREATE_SESSION = 950;
const AUTH_ERROR_UNKNOWN = 999;

const ERROR_READ_CATEGORY = 1001;
const ERROR_INSERT_CATEGORY = 1002;
const ERROR_DELETE_CATEGORY = 1003;
const ERROR_READ_TASK = 1004;
const ERROR_INSERT_TASK = 1005;
const ERROR_DELETE_TASK = 1006;
const ERROR_UPDATE_TASK = 1007;

const INVALID_AUTH_CODE = 1900;
const INVALID_CATEGORY_PARAMETERS = 2001;
const INVALID_CATEGORY_ID = 2002;
const INVALID_TASK_PARAMETERS = 2003;
const INVALID_TASK_ID = 2004;

module.exports = {
  UNAUTHORIZED,
  EXPIRED_SESSION,

  AUTH_INVALID_PAYLOAD,
  AUTH_INVALID_CODE,
  ERROR_CREATE_USER,
  ERROR_CREATE_SESSION,
  AUTH_ERROR_UNKNOWN,

  ERROR_READ_CATEGORY,
  ERROR_INSERT_CATEGORY,
  ERROR_DELETE_CATEGORY,
  ERROR_READ_TASK,
  ERROR_INSERT_TASK,
  ERROR_DELETE_TASK,
  ERROR_UPDATE_TASK,

  INVALID_AUTH_CODE,
  INVALID_CATEGORY_PARAMETERS,
  INVALID_CATEGORY_ID,
  INVALID_TASK_PARAMETERS,
  INVALID_TASK_ID,
};
